export const Url = {
  imageFetchUrl: 'https://image.tmdb.org/t/p/original',
  imageBackgroundFetchUrl: 'https://image.tmdb.org/t/p/w500',
  baseURL: 'https://api.themoviedb.org/3/',
  popularStreaming: 'movie/popular?language=en-US&page=',
  popularRent:
    'discover/movie?watch_region=US&with_watch_monetization_types=rent&page=',
  popularTv: 'tv/popular?language=en-US&page=',
  movieNowPlaying: 'movie/now_playing?language=en-US&page=',
  movieTopRated: 'movie/top_rated?language=en-US&page=',
  movieUpcoming: 'movie/upcoming?language=en-US&page=',
  trendingToday: 'trending/movie/day?language=en-US&page=',
  trendingWeek: 'trending/movie/week?language=en-US&page=',
  trailerDetail: 'movie/550/videos?language=en-US&page=',
  tv: '/tv',
  movie: '/movie',
  videos: '?append_to_response=videos',
  credits: '?append_to_response=credits',
  youtube: 'https://www.youtube.com/watch?v=',
  search: 'https://api.themoviedb.org/3/search/multi?query=',
  movieString: 'movie',
  tvString: 'tv',
  page: '&page=',
};
