export default {
  popular: "What's Popular",
  streaming: 'Streaming',
  freeToWatch: 'Free To Watch',
  movies: 'Movies',
  newMovies: 'New Movies',
  nowPlaying: 'Now Playing',
  topRated: 'Top Rated',
  upcoming: 'Upcoming',
  onTV: 'On TV',
  forRent: 'For Rent',
  inTheaters: 'In Theaters',
  today: 'Today',
  week: 'This Week',
  trending: 'Trending',
  trailer: 'Latest Trailers',
  userScore: 'User Score',
  stopTrailer: 'Stop Trailer',
  playTrailer: 'Play Trailer',
  error: 'Error',
  trailerNotAvailable: 'Trailer is Not Available',
  us: 'US',
  noGenres: 'No Genres Available',
  overview: 'Overview',
  director: 'Director',
  videoTrailer: 'Trailer',
  tryAgain: 'Try Again',
  notAvailable: 'Not Available',
  search: 'Search here...',
  retry: "Couldn't Load, Please retry",
  retryAgain: 'Please retry again',
  signInAgain: 'Sign-In Again',
  couldNotLoad: "Couldn't Load, Refresh to continue",
  email: 'Email',
  phone: 'Phone',
  name: 'Name',
  enterName: 'Enter Name',
  enterEmail: 'Enter Email',
  enterMobileNo: 'Enter Mobile Number',
  enterPassword: 'Enter Password',
  enterConfirmPassword: 'Enter Confirm Password',
  notEmail: 'Please enter a valid email',
  requiredField: 'This is required field',
  notName: 'Please enter valid Name',
  validMobile: 'Enter valid Mobile Number',
  passwordMinimumLength: 'Password should be minimum 8 characters',
  passwordNotMatching: 'Enter exact Password',
  login: 'Login',
  signUp: 'SignUp',
  accNotExist: 'Account not Exist?',
  accExist: 'Already have an Account?',
  userNotFound: "User doesn't Exist",
  userExist: 'User already Exist',
  inCorrectPassword: 'Enter Correct Password',
  logout: 'Logout',
  confirmLogout: 'Are you sure, you want to Logout?',
  cancel: 'Cancel',
  active: 'Active Now',
  send: 'Send',
  personalMessages: 'Your personal messages are ',
  encrypted: 'end-to-end encrypted',
  groupName: 'Enter Group Name',
  groupActivity: 'Active Group',
  groupExist: 'Group Exist',
  messageInGroup: 'Please Message in Existing Group',
  image: 'Image',
  video: 'Video',
  permissionDenied: 'Permission Denied',
  ok: 'okay',
  accessLocation: 'Would you still like to give access to your location?',
  accessCamera: 'Would you still like to give access to your Camera?',
  accessGallery: 'Would you still like to give access to your Gallery?',
};
