export default {
  popular: "What's Popular",
  streaming: 'Streaming',
  freeToWatch: 'Free To Watch',
  movies: 'Movies',
  newMovies: 'New Movies',
  nowPlaying: 'Now Playing',
  topRated: 'Top Rated',
  upcoming: 'Upcoming',
  onTV: 'On TV',
  forRent: 'For Rent',
  inTheaters: 'In Theaters',
  today: 'Today',
  week: 'This Week',
  trending: 'Trending',
  trailer: 'Latest Trailers',
  userScore: 'User Score',
  playTrailer: 'Play Trailer',
  error: 'Error Occurred',
  us: 'US',
  noGenres: 'No Genres Available',
  overview: 'Overview',
  director: 'Director',
  videoTrailer: 'Trailer',
  tryAgain: 'Try Again',
  notAvailable: 'Not Available',
  search: 'Search here...',
};
